### ISSUE TITLE
does the cli work?

### ISSUE THREAD

**Issue by jaredh159** [nlopes/acdc#29]
hey, just wanted to play around with your implementation, but couldn't get the cli to work. i know it's not documented in the readme so maybe its not considered usable, but i saw that `cargo run -- --help` worked, but when i passed it a path to an asciidoc file, i didn't seem to get any output or a file written.

**Comment by nlopes** [comment]
Oh hey 👋 

So, as I've been looking into start of work to actually have backends, I moved the `terminal` implementation I had behind a feature flag (and none of the other backends are working yet).

If you do
```
cargo run --features terminal -- --backend terminal <YOUR .adoc FILE HERE>
```

what's in the `main` branch should work.

Just a heads up that I had hacked most of the code to get to a "barely working" implementation, and now I'm making a few design choices before I clean this into an actual functioning set of tools so there might be breakage (I'll try to document it through the commits/PRs though).

Oh another thing, I've also started work on getting it to pass the TCK tests, which you can run with (from within the `asciidoc-tck` repository and assuming you have a sibling repo with this code in `acdc`:
```
npm exec asciidoc-tck --adapter-mode cli --adapter-command "../acdc/target/debug/acdc-cli --tck-mode"
```

**Comment by jaredh159** [comment]
ok cool thanks!
